version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/df-mc/dragonfly"
    groups:
      dragonfly:
        patterns:
          - "github.com/df-mc/dragonfly"
